create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default 'MelBurb Player'
    check (char_length(display_name) between 1 and 30),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.game_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  game_key text not null,
  mode text not null check (mode in ('daily', 'practice')),
  score integer not null check (score between 0 and 100),
  guesses_count integer not null check (guesses_count between 1 and 6),
  closest_distance_m integer not null check (closest_distance_m >= 0),
  solved boolean not null,
  clue_count integer not null default 0 check (clue_count >= 0),
  played_at timestamptz not null default now(),
  unique (user_id, game_key)
);

alter table public.profiles enable row level security;
alter table public.game_results enable row level security;

create policy "Players can read their own profile"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "Players can update their own profile"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "Players can read their own results"
  on public.game_results for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Players can add their own results"
  on public.game_results for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Players can update their own results"
  on public.game_results for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), 'MelBurb Player')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute procedure public.set_updated_at();
